### ISSUE TITLE
Reset Data Directory Command Failed

### ISSUE THREAD

**Issue by gabriellewp** [Open-IoT-Service-Platform/oisp-iot-agent#3]
here is stack trace 

osboxes@osboxes:~/iotkit-agent/agent$ NODE_ENV=local ./oisp-admin.js reset-data-directory
/home/osboxes/iotkit-agent/agent/lib/common.js:214
        data[keys.pop()] = value;
                         ^

TypeError: Cannot set property 'data_directory' of null
    at configSaver (/home/osboxes/iotkit-agent/agent/lib/common.js:214:26)
    at Object.module.exports.saveToConfig (/home/osboxes/iotkit-agent/agent/lib/common.js:217:12)
    at Object.module.exports.saveToGlobalConfig (/home/osboxes/iotkit-agent/agent/lib/common.js:169:10)
    at Command.<anonymous> (/home/osboxes/iotkit-agent/agent/admin/configurator.js:428:24)
    at Command.listener (/home/osboxes/iotkit-agent/agent/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (/home/osboxes/iotkit-agent/agent/node_modules/commander/index.js:653:12)
    at Command.parse (/home/osboxes/iotkit-agent/agent/node_modules/commander/index.js:475:21)
    at Object.<anonymous> (/home/osboxes/iotkit-agent/agent/bin/admin.js:81:11)

**Comment by srware** [comment]
The mess that is config files...

I think this is a bug from the initial split we did which means it can no longer find the global.json config file to write to as it's now in the SDK package. I'm looking at a better solution for this as part of splitting this into separate repositories. Will update when I have found the solution.

**Comment by srware** [comment]
The config file situation still needs work but this issue should at least be fixed for now.
